apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/component: pipeline
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/part-of: Triggers
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    eventlistener: {{ .Values.app.name }}
  name: el-{{ .Values.app.name }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.app.name }}
  wildcardPolicy: None
