apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitSecret.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Values.app.name }}
  annotations:
    tekton.dev/git-0: {{ .Values.git.serverUrl }}
type: kubernetes.io/basic-auth
data:
  password: {{ .Values.gitSecret.password }}
  username: {{ .Values.gitSecret.username }}